version: "3.9"

services:
  backend:
    build: ./backend
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/storage:/app/storage
    environment:
      - TZ=UTC
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: chatbot_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
