services:
  - type: web
    name: chatbot-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000

  - type: web
    name: chatbot-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
